# Generated by Django 4.2.7 on 2024-02-09 19:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adress', models.CharField(max_length=150)),
                ('area', models.IntegerField()),
                ('state', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDUE', 'Vendue'), ('EN_ATTENTE', 'En Attente'), ('ARCHIVE', 'Archive')], max_length=20)),
                ('type_propriete', models.CharField(choices=[('Villa', 'Villa'), ('Terrain', 'Terrain'), ('Appartement', 'Appartement')], default='NON', max_length=50)),
                ('img_1', models.ImageField(null=True, upload_to='images/')),
                ('img_2', models.ImageField(null=True, upload_to='images/')),
                ('img_3', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('phone', models.CharField(max_length=10, unique=True)),
                ('adress', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('user_type', models.CharField(choices=[('AGENCE', 'Agence'), ('PARTICULIER', 'Particulier')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Store.property')),
                ('rooms', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('bathrooms', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('floors', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('waterfront', models.BooleanField()),
                ('view', models.CharField(choices=[('Excellente', 'Excellente'), ('Bonne', 'Bonne'), ('Normal', 'Normal'), ('Mauvaise', 'Mauvaise')], max_length=20)),
                ('year_built', models.IntegerField()),
                ('year_renovted', models.IntegerField()),
                ('estim_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('Store.property',),
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Store.property')),
                ('Ground_type', models.CharField(choices=[('Agricole', 'Agricole'), ('Forestier', 'Forestier'), ('Urbain', 'Urbain')], max_length=20)),
            ],
            bases=('Store.property',),
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Store.property')),
                ('rooms', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('bathrooms', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('garden', models.BooleanField(null=True)),
                ('pool', models.BooleanField(null=True)),
                ('floors', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('year_built', models.IntegerField()),
            ],
            bases=('Store.property',),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('Property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Store.property')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
