# Generated by Django 4.2.7 on 2024-02-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='estim_price',
        ),
    ]
